[versions]
android-compileSdk = "35"
android-minSdk = "29"
android-targetSdk = "35"
androidx-activity = "1.9.3" # https://developer.android.com/jetpack/androidx/releases/activity
androidx-lifecycle = "2.8.3" # https://developer.android.com/jetpack/androidx/releases/lifecycle
compose-plugin = "1.7.0" # https://github.com/JetBrains/compose-multiplatform/releases
kotlin = "2.0.21" # https://kotlinlang.org/docs/releases.html
kotlinx-coroutines = "1.9.0" # https://github.com/Kotlin/kotlinx.coroutines/releases
kotlinx-serialization = "1.7.3" # https://github.com/Kotlin/kotlinx.serialization/releases
gradle = "8.6.1" # https://developer.android.com/build/releases/gradle-plugin

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-lifecycle-runtime-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
kotlinx-coroutines-swing = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
kotlinx-serialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "gradle" }
androidLibrary = { id = "com.android.library", version.ref = "gradle" }
compose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }